# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

name: ecommerceweb

services:
  ecommerceweb-webapp:
    image: ecommerceweb-webapp:dev
    container_name: ecommerceweb-webapp
    build:
      context: .
      dockerfile: src/Presentation/WebApp/Dockerfile
      args:
        - configuration=Debug
      target: dev
    ports:
      - 6200:8080
      - 6217:8443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${DEV_CERT_PASSWD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  ecommerceweb-public-api:
    image: ecommerceweb-public-api:dev
    container_name: ecommerceweb-public-api
    build:
      context: .
      dockerfile: src/Presentation/PublicServer/Dockerfile
      args:
        - configuration=Debug
      target: dev
    ports:
      - 5200:8080
      - 5217:8443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${DEV_CERT_PASSWD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

networks:
  default:
    name: ecommerceweb-net