name: ecommerceweb

services:
  ecommerceweb-webapp:
    image: ${DOCKER_REGISTRY-}ecommerceweb-webapp:latest
    container_name: ecommerceweb-webapp
    build:
      context: .
      dockerfile: src/Presentation/WebApp/Dockerfile
      target: final
    depends_on:
      - ecommerceweb-db
      - ecommerceweb-cache
      - ecommerceweb-storage
      - ecommerceweb-seq-log-server
    
  ecommerceweb-public-api:
    image: ${DOCKER_REGISTRY-}ecommerceweb-public-api:latest
    container_name: ecommerceweb-public-api
    build:
      context: .
      dockerfile: src/Presentation/PublicApi/Dockerfile
      target: final
    depends_on:
      - ecommerceweb-db
      - ecommerceweb-storage
      - ecommerceweb-seq-log-server
  
  ecommerceweb-db:
    container_name: ecommerceweb-db
    image: postgres:alpine
  
  ecommerceweb-cache:
    container_name: ecommerceweb-cache
    image: redis/redis-stack:latest
  
  ecommerceweb-storage:
    container_name: ecommerceweb-storage
    image: mcr.microsoft.com/azure-storage/azurite:latest
  
  ecommerceweb-seq-log-server:
    container_name: seq-log-server
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y

networks:
  default:
    name: ecommerceweb-net